ALTER TABLE search_profiles
  ADD COLUMN IF NOT EXISTS location_mode TEXT DEFAULT 'city',
  ADD COLUMN IF NOT EXISTS districts TEXT[],
  ADD COLUMN IF NOT EXISTS radius_km INTEGER,
  ADD COLUMN IF NOT EXISTS commute_destination TEXT,
  ADD COLUMN IF NOT EXISTS commute_lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS commute_lng DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS commute_mode TEXT,
  ADD COLUMN IF NOT EXISTS commute_minutes INTEGER;
