ALTER TABLE listings ADD COLUMN IF NOT EXISTS garden BOOLEAN DEFAULT NULL;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS bath BOOLEAN DEFAULT NULL;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS roof_terrace BOOLEAN DEFAULT NULL;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS energy_label TEXT DEFAULT NULL;
ALTER TABLE listings ADD COLUMN IF NOT EXISTS property_type TEXT DEFAULT NULL;
